import React from 'react';
import {mount, shallow, render} from 'enzyme';
import OrderList from './OrderList'
import {Provider} from 'react-redux';
import configureStore from 'redux-mock-store';
import Enzyme from 'enzyme';
import Adapter from 'enzyme-adapter-react-16';
import {Router} from "react-router-dom";
import PropTypes from 'prop-types';
import createRouterContext from 'react-router-test-context'
import thunkMiddleware from "redux-thunk";

const middleWares = [thunkMiddleware];
const mockStore = configureStore(middleWares);
Enzyme.configure({adapter: new Adapter()});

//const mountWithRouter = node => mount(<Router>{node}</Router>);

let orderStore = {

    ordersFilterReducer: {
        "paidFor": false,
        "pageNumber": 1
    },
    ordersByFilter: {
        isFetching: false,

        "responseStatus": "OK",
        "responseMessage": null,
        "timestamp": "2018-04-23T20:13:17+0100",
        orders: {
            "OutgoingOrders": {
                "Order": [
                    {
                        "OrderType": "Order",
                        "OrderSource": "Manual",
                        "ESPOrderNo": 1000,
                        "InvoiceNumber": null,
                        "ExternalReference": null,
                        "Date": "2016-12-15T10:46:18+0000",
                        "CustomerCompany": "",
                        "CustomerName": "",
                        "CustomerAddress1": "",
                        "CustomerAddress2": "",
                        "CustomerAddress3": null,
                        "CustomerCity": "",
                        "CustomerCounty": "",
                        "CustomerPostcode": "",
                        "CustomerCountry": "UK",
                        "CustomerEmail": "",
                        "CustomerTelephone": "",
                        "CustomerFax": null,
                        "CustomerReference": null,
                        "CustomerNotes": null,
                        "DeliveryCompany": "",
                        "DeliveryName": "",
                        "DeliveryAddress1": "",
                        "DeliveryAddress2": "",
                        "DeliveryAddress3": null,
                        "DeliveryCity": "",
                        "DeliveryCounty": "",
                        "DeliveryPostcode": "",
                        "DeliveryCountry": "UK",
                        "DeliveryTelephone": "",
                        "ShippingMethod": null,
                        "ShippingCost": 0,
                        "Insurance": 0,
                        "Discount": 0,
                        "VoucherCode": null,
                        "OrderTotal": 0,
                        "PaymentComplete": true,
                        "Payments": null,
                        "CurrencyCode": "GBP",
                        "SellerUsername": null,
                        "CourierProfileName": null,
                        "OrderItems": {
                            "Item": [
                                {
                                    "WebProductID": "0",
                                    "StockNumber": "",
                                    "ItemNumber": "0",
                                    "ProductTitle": "",
                                    "Quantity": 0,
                                    "UnitCost": 0,
                                    "TaxRate": 20,
                                    "TaxCode": null,
                                    "UnitCostIncludesTax": "Y",
                                    "Weight": 0,
                                    "ProductFolderName": null,
                                    "CreditReason": null,
                                    "CustomMessage1": null,
                                    "CustomMessage2": null,
                                    "CustomMessage3": null,
                                    "LocationId": 0
                                }
                            ]
                        },
                        "BuyerId": "",
                        "StoreId": null,
                        "ShipToStore": null,
                        "OrderCredits": null,
                        "OrderStatus": "Delivered",
                        "Flag1": null,
                        "Flag2": null,
                        "CourierName": null,
                        "CourierService": null,
                        "CourierServiceCode": null,
                        "FulfilmentType": "MERCHANT"
                    },
                    {
                        "OrderType": "Order",
                        "OrderSource": "WWW",
                        "ESPOrderNo": 1001,
                        "InvoiceNumber": "41220",
                        "ExternalReference": "100000136",
                        "Date": "2016-12-16T11:20:11+0000",
                        "CustomerCompany": "",
                        "CustomerName": "Simeone Zaza",
                        "CustomerAddress1": "53343 Turin Road",
                        "CustomerAddress2": "",
                        "CustomerAddress3": null,
                        "CustomerCity": "Atlanta",
                        "CustomerCounty": "Georgia",
                        "CustomerPostcode": "32423",
                        "CustomerCountry": "US",
                        "CustomerEmail": "1481275517@example.com",
                        "CustomerTelephone": "32342432",
                        "CustomerFax": null,
                        "CustomerReference": null,
                        "CustomerNotes": "0",
                        "DeliveryCompany": "",
                        "DeliveryName": "Simeone Zaza",
                        "DeliveryAddress1": "53343 Turin Road",
                        "DeliveryAddress2": "",
                        "DeliveryAddress3": null,
                        "DeliveryCity": "Atlanta",
                        "DeliveryCounty": "Georgia",
                        "DeliveryPostcode": "32423",
                        "DeliveryCountry": "US",
                        "DeliveryTelephone": "32342432",
                        "ShippingMethod": "flatrate_flatrate",
                        "ShippingCost": 5,
                        "Insurance": 0,
                        "Discount": 0,
                        "VoucherCode": null,
                        "OrderTotal": 105,
                        "PaymentComplete": true,
                        "Payments": {
                            "Payment": [
                                {
                                    "PaymentMethod": "Credit Card",
                                    "PaymentReference": "cashondelivery ",
                                    "PaymentNotes": null,
                                    "PaymentCCDetails": null,
                                    "PaymentGateway": null,
                                    "PayPalEmail": null,
                                    "PayPalTransactionID": null,
                                    "PayPalProtectionEligibility": false,
                                    "Amount": 105,
                                    "PaymentDate": "2016-12-16T00:00:00+0000"
                                }
                            ]
                        },
                        "CurrencyCode": "GBP",
                        "SellerUsername": "Magento Test Site",
                        "CourierProfileName": null,
                        "OrderItems": {
                            "Item": [
                                {
                                    "WebProductID": "22",
                                    "StockNumber": "AZ11",
                                    "ItemNumber": "176",
                                    "ProductTitle": "Kawasaki H2R 800cc",
                                    "Quantity": 1,
                                    "UnitCost": 100,
                                    "TaxRate": 40,
                                    "TaxCode": null,
                                    "UnitCostIncludesTax": "Y",
                                    "Weight": 0,
                                    "ProductFolderName": null,
                                    "CreditReason": null,
                                    "CustomMessage1": null,
                                    "CustomMessage2": null,
                                    "CustomMessage3": null,
                                    "LocationId": 4
                                }
                            ]
                        },
                        "BuyerId": "",
                        "StoreId": null,
                        "ShipToStore": null,
                        "OrderCredits": null,
                        "OrderStatus": "Delivered",
                        "Flag1": null,
                        "Flag2": null,
                        "CourierName": null,
                        "CourierService": null,
                        "CourierServiceCode": null,
                        "FulfilmentType": "MERCHANT"
                    },
                    {
                        "OrderType": "Order",
                        "OrderSource": "Manual",
                        "ESPOrderNo": 1002,
                        "InvoiceNumber": "41221",
                        "ExternalReference": "",
                        "Date": "2016-12-16T13:41:22+0000",
                        "CustomerCompany": "",
                        "CustomerName": "example",
                        "CustomerAddress1": "example",
                        "CustomerAddress2": "example",
                        "CustomerAddress3": null,
                        "CustomerCity": "example",
                        "CustomerCounty": "example",
                        "CustomerPostcode": "BS11 1NS",
                        "CustomerCountry": "UK",
                        "CustomerEmail": "example@example.com",
                        "CustomerTelephone": "",
                        "CustomerFax": null,
                        "CustomerReference": null,
                        "CustomerNotes": null,
                        "DeliveryCompany": "",
                        "DeliveryName": "example",
                        "DeliveryAddress1": "example",
                        "DeliveryAddress2": "example",
                        "DeliveryAddress3": null,
                        "DeliveryCity": "example",
                        "DeliveryCounty": "example",
                        "DeliveryPostcode": "BS11 1NS",
                        "DeliveryCountry": "UK",
                        "DeliveryTelephone": "",
                        "ShippingMethod": null,
                        "ShippingCost": 0,
                        "Insurance": 0,
                        "Discount": 0,
                        "VoucherCode": null,
                        "OrderTotal": 0,
                        "PaymentComplete": true,
                        "Payments": {
                            "Payment": [
                                {
                                    "PaymentMethod": "Cash",
                                    "PaymentReference": "1002",
                                    "PaymentNotes": null,
                                    "PaymentCCDetails": null,
                                    "PaymentGateway": null,
                                    "PayPalEmail": null,
                                    "PayPalTransactionID": null,
                                    "PayPalProtectionEligibility": false,
                                    "Amount": 10,
                                    "PaymentDate": "2016-12-16T00:00:00+0000"
                                },
                                {
                                    "PaymentMethod": "Cash",
                                    "PaymentReference": "1002 Refund",
                                    "PaymentNotes": null,
                                    "PaymentCCDetails": null,
                                    "PaymentGateway": null,
                                    "PayPalEmail": null,
                                    "PayPalTransactionID": null,
                                    "PayPalProtectionEligibility": false,
                                    "Amount": -10,
                                    "PaymentDate": "2016-12-16T00:00:00+0000"
                                }
                            ]
                        },
                        "CurrencyCode": "GBP",
                        "SellerUsername": "testuser_esptestus1",
                        "CourierProfileName": null,
                        "OrderItems": {
                            "Item": [
                                {
                                    "WebProductID": "12",
                                    "StockNumber": "AZ04",
                                    "ItemNumber": "0",
                                    "ProductTitle": "Husqvarna Nuda 900rr - Test",
                                    "Quantity": 1,
                                    "UnitCost": 10,
                                    "TaxRate": 20,
                                    "TaxCode": null,
                                    "UnitCostIncludesTax": "Y",
                                    "Weight": 0,
                                    "ProductFolderName": null,
                                    "CreditReason": null,
                                    "CustomMessage1": null,
                                    "CustomMessage2": null,
                                    "CustomMessage3": null,
                                    "LocationId": 4
                                }
                            ]
                        },
                        "BuyerId": "",
                        "StoreId": null,
                        "ShipToStore": null,
                        "OrderCredits": null,
                        "OrderStatus": "Cancelled",
                        "Flag1": null,
                        "Flag2": null,
                        "CourierName": null,
                        "CourierService": null,
                        "CourierServiceCode": null,
                        "FulfilmentType": "MERCHANT"
                    },
                    {
                        "OrderType": "Order",
                        "OrderSource": "WWW",
                        "ESPOrderNo": 1003,
                        "InvoiceNumber": "41222",
                        "ExternalReference": "100000137",
                        "Date": "2016-12-19T13:29:18+0000",
                        "CustomerCompany": "",
                        "CustomerName": "Simeone Zaza",
                        "CustomerAddress1": "53343 Turin Road",
                        "CustomerAddress2": "",
                        "CustomerAddress3": null,
                        "CustomerCity": "Atlanta",
                        "CustomerCounty": "",
                        "CustomerPostcode": "32423",
                        "CustomerCountry": "GB",
                        "CustomerEmail": "1481275517@example.com",
                        "CustomerTelephone": "32342432",
                        "CustomerFax": null,
                        "CustomerReference": null,
                        "CustomerNotes": "0",
                        "DeliveryCompany": "",
                        "DeliveryName": "Simeone Zaza",
                        "DeliveryAddress1": "53343 Turin Road",
                        "DeliveryAddress2": "",
                        "DeliveryAddress3": null,
                        "DeliveryCity": "Atlanta",
                        "DeliveryCounty": "",
                        "DeliveryPostcode": "32423",
                        "DeliveryCountry": "GB",
                        "DeliveryTelephone": "32342432",
                        "ShippingMethod": "flatrate_flatrate",
                        "ShippingCost": 5,
                        "Insurance": 0,
                        "Discount": 0,
                        "VoucherCode": null,
                        "OrderTotal": 0,
                        "PaymentComplete": false,
                        "Payments": {
                            "Payment": [
                                {
                                    "PaymentMethod": "Credit Card",
                                    "PaymentReference": "cashondelivery ",
                                    "PaymentNotes": null,
                                    "PaymentCCDetails": null,
                                    "PaymentGateway": null,
                                    "PayPalEmail": null,
                                    "PayPalTransactionID": null,
                                    "PayPalProtectionEligibility": false,
                                    "Amount": 40,
                                    "PaymentDate": "2016-12-19T00:00:00+0000"
                                },
                                {
                                    "PaymentMethod": "Credit Card",
                                    "PaymentReference": null,
                                    "PaymentNotes": null,
                                    "PaymentCCDetails": null,
                                    "PaymentGateway": null,
                                    "PayPalEmail": null,
                                    "PayPalTransactionID": null,
                                    "PayPalProtectionEligibility": false,
                                    "Amount": -40,
                                    "PaymentDate": "2016-12-19T00:00:00+0000"
                                }
                            ]
                        },
                        "CurrencyCode": "GBP",
                        "SellerUsername": "Magento Test Site",
                        "CourierProfileName": null,
                        "OrderItems": {
                            "Item": [
                                {
                                    "WebProductID": "19",
                                    "StockNumber": "AZ08",
                                    "ItemNumber": "177",
                                    "ProductTitle": "Honda MSX 125",
                                    "Quantity": 1,
                                    "UnitCost": 35,
                                    "TaxRate": 20,
                                    "TaxCode": null,
                                    "UnitCostIncludesTax": "Y",
                                    "Weight": 0,
                                    "ProductFolderName": null,
                                    "CreditReason": null,
                                    "CustomMessage1": null,
                                    "CustomMessage2": null,
                                    "CustomMessage3": null,
                                    "LocationId": 3
                                }
                            ]
                        },
                        "BuyerId": "",
                        "StoreId": null,
                        "ShipToStore": null,
                        "OrderCredits": null,
                        "OrderStatus": "Cancelled",
                        "Flag1": null,
                        "Flag2": null,
                        "CourierName": null,
                        "CourierService": null,
                        "CourierServiceCode": null,
                        "FulfilmentType": "MERCHANT"
                    },
                    {
                        "OrderType": "Order",
                        "OrderSource": "WWW",
                        "ESPOrderNo": 1004,
                        "InvoiceNumber": "41223",
                        "ExternalReference": "100000138",
                        "Date": "2016-12-19T14:28:33+0000",
                        "CustomerCompany": "",
                        "CustomerName": "Simeone Zaza",
                        "CustomerAddress1": "53343 Turin Road",
                        "CustomerAddress2": "",
                        "CustomerAddress3": null,
                        "CustomerCity": "Atlanta",
                        "CustomerCounty": "Georgia",
                        "CustomerPostcode": "32423",
                        "CustomerCountry": "US",
                        "CustomerEmail": "1481275517@example.com",
                        "CustomerTelephone": "32342432",
                        "CustomerFax": null,
                        "CustomerReference": null,
                        "CustomerNotes": "23-Apr-2018 12:14:57: aasa\n23-Apr-2018 12:14:24: asaaaa\n23-Apr-2018 12:06:58: aac\n23-Apr-2018 12:05:58: asaaaa\n23-Apr-2018 11:57:36: sddsd\n0",
                        "DeliveryCompany": "",
                        "DeliveryName": "Simeone Zaza",
                        "DeliveryAddress1": "53343 Turin Road",
                        "DeliveryAddress2": "",
                        "DeliveryAddress3": null,
                        "DeliveryCity": "Atlanta",
                        "DeliveryCounty": "Georgia",
                        "DeliveryPostcode": "32423",
                        "DeliveryCountry": "US",
                        "DeliveryTelephone": "32342432",
                        "ShippingMethod": "flatrate_flatrate",
                        "ShippingCost": 5,
                        "Insurance": 0,
                        "Discount": 0,
                        "VoucherCode": null,
                        "OrderTotal": 40,
                        "PaymentComplete": true,
                        "Payments": {
                            "Payment": [
                                {
                                    "PaymentMethod": "Credit Card",
                                    "PaymentReference": "cashondelivery ",
                                    "PaymentNotes": null,
                                    "PaymentCCDetails": null,
                                    "PaymentGateway": null,
                                    "PayPalEmail": null,
                                    "PayPalTransactionID": null,
                                    "PayPalProtectionEligibility": false,
                                    "Amount": 40,
                                    "PaymentDate": "2016-12-19T00:00:00+0000"
                                }
                            ]
                        },
                        "CurrencyCode": "GBP",
                        "SellerUsername": "Magento Test Site",
                        "CourierProfileName": null,
                        "OrderItems": {
                            "Item": [
                                {
                                    "WebProductID": "19",
                                    "StockNumber": "AZ08",
                                    "ItemNumber": "178",
                                    "ProductTitle": "Honda MSX 125",
                                    "Quantity": 1,
                                    "UnitCost": 35,
                                    "TaxRate": 40,
                                    "TaxCode": null,
                                    "UnitCostIncludesTax": "Y",
                                    "Weight": 0,
                                    "ProductFolderName": null,
                                    "CreditReason": null,
                                    "CustomMessage1": null,
                                    "CustomMessage2": null,
                                    "CustomMessage3": null,
                                    "LocationId": 4
                                }
                            ]
                        },
                        "BuyerId": "",
                        "StoreId": null,
                        "ShipToStore": null,
                        "OrderCredits": null,
                        "OrderStatus": "On Hold",
                        "Flag1": null,
                        "Flag2": null,
                        "CourierName": null,
                        "CourierService": null,
                        "CourierServiceCode": null,
                        "FulfilmentType": "MERCHANT"
                    },
                    {
                        "OrderType": "Order",
                        "OrderSource": "WWW",
                        "ESPOrderNo": 1005,
                        "InvoiceNumber": "41224",
                        "ExternalReference": "100000139",
                        "Date": "2016-12-19T14:32:31+0000",
                        "CustomerCompany": "",
                        "CustomerName": "Simeone Zaza",
                        "CustomerAddress1": "53343 Turin Road",
                        "CustomerAddress2": "",
                        "CustomerAddress3": null,
                        "CustomerCity": "Atlanta",
                        "CustomerCounty": "Baden-Württemberg",
                        "CustomerPostcode": "32423",
                        "CustomerCountry": "DE",
                        "CustomerEmail": "1481275517@example.com",
                        "CustomerTelephone": "32342432",
                        "CustomerFax": null,
                        "CustomerReference": null,
                        "CustomerNotes": "23-Apr-2018 13:55:02: asd\n0",
                        "DeliveryCompany": "",
                        "DeliveryName": "Simeone Zaza",
                        "DeliveryAddress1": "53343 Turin Road",
                        "DeliveryAddress2": "",
                        "DeliveryAddress3": null,
                        "DeliveryCity": "Atlanta",
                        "DeliveryCounty": "Baden-Württemberg",
                        "DeliveryPostcode": "32423",
                        "DeliveryCountry": "DE",
                        "DeliveryTelephone": "32342432",
                        "ShippingMethod": "flatrate_flatrate",
                        "ShippingCost": 5,
                        "Insurance": 0,
                        "Discount": 0,
                        "VoucherCode": null,
                        "OrderTotal": 40,
                        "PaymentComplete": true,
                        "Payments": {
                            "Payment": [
                                {
                                    "PaymentMethod": "Credit Card",
                                    "PaymentReference": "cashondelivery ",
                                    "PaymentNotes": null,
                                    "PaymentCCDetails": null,
                                    "PaymentGateway": null,
                                    "PayPalEmail": null,
                                    "PayPalTransactionID": null,
                                    "PayPalProtectionEligibility": false,
                                    "Amount": 40,
                                    "PaymentDate": "2016-12-19T00:00:00+0000"
                                }
                            ]
                        },
                        "CurrencyCode": "GBP",
                        "SellerUsername": "Magento Test Site",
                        "CourierProfileName": null,
                        "OrderItems": {
                            "Item": [
                                {
                                    "WebProductID": "19",
                                    "StockNumber": "AZ08",
                                    "ItemNumber": "179",
                                    "ProductTitle": "Honda MSX 125",
                                    "Quantity": 1,
                                    "UnitCost": 35,
                                    "TaxRate": 50,
                                    "TaxCode": null,
                                    "UnitCostIncludesTax": "Y",
                                    "Weight": 0,
                                    "ProductFolderName": null,
                                    "CreditReason": null,
                                    "CustomMessage1": null,
                                    "CustomMessage2": null,
                                    "CustomMessage3": null,
                                    "LocationId": 3
                                }
                            ]
                        },
                        "BuyerId": "",
                        "StoreId": null,
                        "ShipToStore": null,
                        "OrderCredits": null,
                        "OrderStatus": "On Hold",
                        "Flag1": null,
                        "Flag2": null,
                        "CourierName": null,
                        "CourierService": null,
                        "CourierServiceCode": null,
                        "FulfilmentType": "MERCHANT"
                    },
                    {
                        "OrderType": "Order",
                        "OrderSource": "WWW",
                        "ESPOrderNo": 1006,
                        "InvoiceNumber": "41225",
                        "ExternalReference": "100000140",
                        "Date": "2016-12-19T14:35:46+0000",
                        "CustomerCompany": "",
                        "CustomerName": "Simeone Zaza",
                        "CustomerAddress1": "53343 Turin Road",
                        "CustomerAddress2": "",
                        "CustomerAddress3": null,
                        "CustomerCity": "Atlanta",
                        "CustomerCounty": "Georgia",
                        "CustomerPostcode": "32423",
                        "CustomerCountry": "US",
                        "CustomerEmail": "1481275517@example.com",
                        "CustomerTelephone": "32342432",
                        "CustomerFax": null,
                        "CustomerReference": null,
                        "CustomerNotes": "23-Apr-2018 12:41:04: sds\n23-Apr-2018 12:37:31: asasa\n23-Apr-2018 12:37:21: asasa\n0",
                        "DeliveryCompany": "",
                        "DeliveryName": "Simeone Zaza",
                        "DeliveryAddress1": "53343 Turin Road",
                        "DeliveryAddress2": "",
                        "DeliveryAddress3": null,
                        "DeliveryCity": "Atlanta",
                        "DeliveryCounty": "Georgia",
                        "DeliveryPostcode": "32423",
                        "DeliveryCountry": "US",
                        "DeliveryTelephone": "32342432",
                        "ShippingMethod": "flatrate_flatrate",
                        "ShippingCost": 5,
                        "Insurance": 0,
                        "Discount": 0,
                        "VoucherCode": null,
                        "OrderTotal": 40,
                        "PaymentComplete": true,
                        "Payments": {
                            "Payment": [
                                {
                                    "PaymentMethod": "Credit Card",
                                    "PaymentReference": "cashondelivery ",
                                    "PaymentNotes": null,
                                    "PaymentCCDetails": null,
                                    "PaymentGateway": null,
                                    "PayPalEmail": null,
                                    "PayPalTransactionID": null,
                                    "PayPalProtectionEligibility": false,
                                    "Amount": 40,
                                    "PaymentDate": "2016-12-19T00:00:00+0000"
                                }
                            ]
                        },
                        "CurrencyCode": "GBP",
                        "SellerUsername": "Magento Test Site",
                        "CourierProfileName": null,
                        "OrderItems": {
                            "Item": [
                                {
                                    "WebProductID": "19",
                                    "StockNumber": "AZ08",
                                    "ItemNumber": "180",
                                    "ProductTitle": "Honda MSX 125",
                                    "Quantity": 1,
                                    "UnitCost": 35,
                                    "TaxRate": 40,
                                    "TaxCode": null,
                                    "UnitCostIncludesTax": "Y",
                                    "Weight": 0,
                                    "ProductFolderName": null,
                                    "CreditReason": null,
                                    "CustomMessage1": null,
                                    "CustomMessage2": null,
                                    "CustomMessage3": null,
                                    "LocationId": 4
                                }
                            ]
                        },
                        "BuyerId": "",
                        "StoreId": null,
                        "ShipToStore": null,
                        "OrderCredits": null,
                        "OrderStatus": "On Hold",
                        "Flag1": null,
                        "Flag2": null,
                        "CourierName": null,
                        "CourierService": null,
                        "CourierServiceCode": null,
                        "FulfilmentType": "MERCHANT"
                    },
                    {
                        "OrderType": "Order",
                        "OrderSource": "WWW",
                        "ESPOrderNo": 1007,
                        "InvoiceNumber": "41226",
                        "ExternalReference": "100000141",
                        "Date": "2016-12-19T14:41:45+0000",
                        "CustomerCompany": "",
                        "CustomerName": "Simeone Zaza",
                        "CustomerAddress1": "53343 Turin Road",
                        "CustomerAddress2": "",
                        "CustomerAddress3": null,
                        "CustomerCity": "Atlanta",
                        "CustomerCounty": "Georgia",
                        "CustomerPostcode": "32423",
                        "CustomerCountry": "US",
                        "CustomerEmail": "1481275517@example.com",
                        "CustomerTelephone": "32342432",
                        "CustomerFax": null,
                        "CustomerReference": null,
                        "CustomerNotes": "0",
                        "DeliveryCompany": "",
                        "DeliveryName": "Simeone Zaza",
                        "DeliveryAddress1": "53343 Turin Road",
                        "DeliveryAddress2": "",
                        "DeliveryAddress3": null,
                        "DeliveryCity": "Atlanta",
                        "DeliveryCounty": "Georgia",
                        "DeliveryPostcode": "32423",
                        "DeliveryCountry": "US",
                        "DeliveryTelephone": "32342432",
                        "ShippingMethod": "flatrate_flatrate",
                        "ShippingCost": 5,
                        "Insurance": 0,
                        "Discount": 0,
                        "VoucherCode": null,
                        "OrderTotal": 40,
                        "PaymentComplete": true,
                        "Payments": {
                            "Payment": [
                                {
                                    "PaymentMethod": "Credit Card",
                                    "PaymentReference": "cashondelivery ",
                                    "PaymentNotes": null,
                                    "PaymentCCDetails": null,
                                    "PaymentGateway": null,
                                    "PayPalEmail": null,
                                    "PayPalTransactionID": null,
                                    "PayPalProtectionEligibility": false,
                                    "Amount": 40,
                                    "PaymentDate": "2016-12-19T00:00:00+0000"
                                }
                            ]
                        },
                        "CurrencyCode": "GBP",
                        "SellerUsername": "Magento Test Site",
                        "CourierProfileName": null,
                        "OrderItems": {
                            "Item": [
                                {
                                    "WebProductID": "19",
                                    "StockNumber": "AZ08",
                                    "ItemNumber": "181",
                                    "ProductTitle": "Honda MSX 125",
                                    "Quantity": 1,
                                    "UnitCost": 35,
                                    "TaxRate": 40,
                                    "TaxCode": null,
                                    "UnitCostIncludesTax": "Y",
                                    "Weight": 0,
                                    "ProductFolderName": null,
                                    "CreditReason": null,
                                    "CustomMessage1": null,
                                    "CustomMessage2": null,
                                    "CustomMessage3": null,
                                    "LocationId": 3
                                }
                            ]
                        },
                        "BuyerId": "",
                        "StoreId": null,
                        "ShipToStore": null,
                        "OrderCredits": null,
                        "OrderStatus": "Delivered",
                        "Flag1": null,
                        "Flag2": null,
                        "CourierName": null,
                        "CourierService": null,
                        "CourierServiceCode": null,
                        "FulfilmentType": "MERCHANT"
                    },
                    {
                        "OrderType": "Order",
                        "OrderSource": "WWW",
                        "ESPOrderNo": 1008,
                        "InvoiceNumber": "41227",
                        "ExternalReference": "100000142",
                        "Date": "2016-12-19T14:50:05+0000",
                        "CustomerCompany": "",
                        "CustomerName": "Simeone Zaza",
                        "CustomerAddress1": "53343 Turin Road",
                        "CustomerAddress2": "",
                        "CustomerAddress3": null,
                        "CustomerCity": "Atlanta",
                        "CustomerCounty": "",
                        "CustomerPostcode": "32423",
                        "CustomerCountry": "GB",
                        "CustomerEmail": "1481275517@example.com",
                        "CustomerTelephone": "32342432",
                        "CustomerFax": null,
                        "CustomerReference": null,
                        "CustomerNotes": "0",
                        "DeliveryCompany": "",
                        "DeliveryName": "Simeone Zaza",
                        "DeliveryAddress1": "53343 Turin Road",
                        "DeliveryAddress2": "",
                        "DeliveryAddress3": null,
                        "DeliveryCity": "Atlanta",
                        "DeliveryCounty": "",
                        "DeliveryPostcode": "32423",
                        "DeliveryCountry": "GB",
                        "DeliveryTelephone": "32342432",
                        "ShippingMethod": "flatrate_flatrate",
                        "ShippingCost": 60,
                        "Insurance": 0,
                        "Discount": 0,
                        "VoucherCode": null,
                        "OrderTotal": 540,
                        "PaymentComplete": true,
                        "Payments": {
                            "Payment": [
                                {
                                    "PaymentMethod": "Cash",
                                    "PaymentReference": "",
                                    "PaymentNotes": null,
                                    "PaymentCCDetails": null,
                                    "PaymentGateway": null,
                                    "PayPalEmail": null,
                                    "PayPalTransactionID": null,
                                    "PayPalProtectionEligibility": false,
                                    "Amount": 540,
                                    "PaymentDate": "2016-12-19T00:00:00+0000"
                                }
                            ]
                        },
                        "CurrencyCode": "GBP",
                        "SellerUsername": "Magento Test Site",
                        "CourierProfileName": null,
                        "OrderItems": {
                            "Item": [
                                {
                                    "WebProductID": "114",
                                    "StockNumber": "AZ07#sku",
                                    "ItemNumber": "182",
                                    "ProductTitle": "Lexmoto ZSXF 125",
                                    "Quantity": 12,
                                    "UnitCost": 40,
                                    "TaxRate": 20,
                                    "TaxCode": null,
                                    "UnitCostIncludesTax": "Y",
                                    "Weight": 0,
                                    "ProductFolderName": null,
                                    "CreditReason": null,
                                    "CustomMessage1": null,
                                    "CustomMessage2": null,
                                    "CustomMessage3": null,
                                    "LocationId": 0
                                }
                            ]
                        },
                        "BuyerId": "",
                        "StoreId": null,
                        "ShipToStore": null,
                        "OrderCredits": null,
                        "OrderStatus": "Delivered",
                        "Flag1": null,
                        "Flag2": null,
                        "CourierName": null,
                        "CourierService": null,
                        "CourierServiceCode": null,
                        "FulfilmentType": "MERCHANT"
                    },
                    {
                        "OrderType": "Order",
                        "OrderSource": "WWW",
                        "ESPOrderNo": 1009,
                        "InvoiceNumber": "41228",
                        "ExternalReference": "100000143",
                        "Date": "2016-12-19T14:58:30+0000",
                        "CustomerCompany": "",
                        "CustomerName": "Simeone Zaza",
                        "CustomerAddress1": "53343 Turin Road",
                        "CustomerAddress2": "",
                        "CustomerAddress3": null,
                        "CustomerCity": "Atlanta",
                        "CustomerCounty": "",
                        "CustomerPostcode": "32423",
                        "CustomerCountry": "GB",
                        "CustomerEmail": "1481275517@example.com",
                        "CustomerTelephone": "32342432",
                        "CustomerFax": null,
                        "CustomerReference": null,
                        "CustomerNotes": "0",
                        "DeliveryCompany": "",
                        "DeliveryName": "Simeone Zaza",
                        "DeliveryAddress1": "53343 Turin Road",
                        "DeliveryAddress2": "",
                        "DeliveryAddress3": null,
                        "DeliveryCity": "Atlanta",
                        "DeliveryCounty": "",
                        "DeliveryPostcode": "32423",
                        "DeliveryCountry": "GB",
                        "DeliveryTelephone": "32342432",
                        "ShippingMethod": "flatrate_flatrate",
                        "ShippingCost": 5,
                        "Insurance": 0,
                        "Discount": 0,
                        "VoucherCode": null,
                        "OrderTotal": 45,
                        "PaymentComplete": true,
                        "Payments": {
                            "Payment": [
                                {
                                    "PaymentMethod": "Credit Card",
                                    "PaymentReference": "cashondelivery ",
                                    "PaymentNotes": null,
                                    "PaymentCCDetails": null,
                                    "PaymentGateway": null,
                                    "PayPalEmail": null,
                                    "PayPalTransactionID": null,
                                    "PayPalProtectionEligibility": false,
                                    "Amount": 45,
                                    "PaymentDate": "2016-12-19T00:00:00+0000"
                                }
                            ]
                        },
                        "CurrencyCode": "GBP",
                        "SellerUsername": "Magento Test Site",
                        "CourierProfileName": null,
                        "OrderItems": {
                            "Item": [
                                {
                                    "WebProductID": "114",
                                    "StockNumber": "AZ07#sku",
                                    "ItemNumber": "183",
                                    "ProductTitle": "Lexmoto ZSXF 125",
                                    "Quantity": 1,
                                    "UnitCost": 40,
                                    "TaxRate": 20,
                                    "TaxCode": null,
                                    "UnitCostIncludesTax": "Y",
                                    "Weight": 0,
                                    "ProductFolderName": null,
                                    "CreditReason": null,
                                    "CustomMessage1": null,
                                    "CustomMessage2": null,
                                    "CustomMessage3": null,
                                    "LocationId": 3
                                }
                            ]
                        },
                        "BuyerId": "",
                        "StoreId": null,
                        "ShipToStore": null,
                        "OrderCredits": null,
                        "OrderStatus": "Delivered",
                        "Flag1": null,
                        "Flag2": null,
                        "CourierName": null,
                        "CourierService": null,
                        "CourierServiceCode": null,
                        "FulfilmentType": "MERCHANT"
                    }
                ]
            },
            "PaginationResult": {
                "TotalNumberOfPages": 339,
                "TotalNumberOfEntries": 3382
            }

        }
    }
};

jest.mock('cross-fetch', () => {
let order = {
    "OutgoingOrders": {
        "Order": [
            {
                "OrderType": "Order",
                "OrderSource": "Manual",
                "ESPOrderNo": 1000,
                "InvoiceNumber": null,
                "ExternalReference": null,
                "Date": "2016-12-15T10:46:18+0000",
                "CustomerCompany": "",
                "CustomerName": "",
                "CustomerAddress1": "",
                "CustomerAddress2": "",
                "CustomerAddress3": null,
                "CustomerCity": "",
                "CustomerCounty": "",
                "CustomerPostcode": "",
                "CustomerCountry": "UK",
                "CustomerEmail": "",
                "CustomerTelephone": "",
                "CustomerFax": null,
                "CustomerReference": null,
                "CustomerNotes": null,
                "DeliveryCompany": "",
                "DeliveryName": "",
                "DeliveryAddress1": "",
                "DeliveryAddress2": "",
                "DeliveryAddress3": null,
                "DeliveryCity": "",
                "DeliveryCounty": "",
                "DeliveryPostcode": "",
                "DeliveryCountry": "UK",
                "DeliveryTelephone": "",
                "ShippingMethod": null,
                "ShippingCost": 0,
                "Insurance": 0,
                "Discount": 0,
                "VoucherCode": null,
                "OrderTotal": 0,
                "PaymentComplete": true,
                "Payments": null,
                "CurrencyCode": "GBP",
                "SellerUsername": null,
                "CourierProfileName": null,
                "OrderItems": {
                    "Item": [
                        {
                            "WebProductID": "0",
                            "StockNumber": "",
                            "ItemNumber": "0",
                            "ProductTitle": "",
                            "Quantity": 0,
                            "UnitCost": 0,
                            "TaxRate": 20,
                            "TaxCode": null,
                            "UnitCostIncludesTax": "Y",
                            "Weight": 0,
                            "ProductFolderName": null,
                            "CreditReason": null,
                            "CustomMessage1": null,
                            "CustomMessage2": null,
                            "CustomMessage3": null,
                            "LocationId": 0
                        }
                    ]
                },
                "BuyerId": "",
                "StoreId": null,
                "ShipToStore": null,
                "OrderCredits": null,
                "OrderStatus": "Delivered",
                "Flag1": null,
                "Flag2": null,
                "CourierName": null,
                "CourierService": null,
                "CourierServiceCode": null,
                "FulfilmentType": "MERCHANT"
            },
            {
                "OrderType": "Order",
                "OrderSource": "WWW",
                "ESPOrderNo": 1001,
                "InvoiceNumber": "41220",
                "ExternalReference": "100000136",
                "Date": "2016-12-16T11:20:11+0000",
                "CustomerCompany": "",
                "CustomerName": "Simeone Zaza",
                "CustomerAddress1": "53343 Turin Road",
                "CustomerAddress2": "",
                "CustomerAddress3": null,
                "CustomerCity": "Atlanta",
                "CustomerCounty": "Georgia",
                "CustomerPostcode": "32423",
                "CustomerCountry": "US",
                "CustomerEmail": "1481275517@example.com",
                "CustomerTelephone": "32342432",
                "CustomerFax": null,
                "CustomerReference": null,
                "CustomerNotes": "0",
                "DeliveryCompany": "",
                "DeliveryName": "Simeone Zaza",
                "DeliveryAddress1": "53343 Turin Road",
                "DeliveryAddress2": "",
                "DeliveryAddress3": null,
                "DeliveryCity": "Atlanta",
                "DeliveryCounty": "Georgia",
                "DeliveryPostcode": "32423",
                "DeliveryCountry": "US",
                "DeliveryTelephone": "32342432",
                "ShippingMethod": "flatrate_flatrate",
                "ShippingCost": 5,
                "Insurance": 0,
                "Discount": 0,
                "VoucherCode": null,
                "OrderTotal": 105,
                "PaymentComplete": true,
                "Payments": {
                    "Payment": [
                        {
                            "PaymentMethod": "Credit Card",
                            "PaymentReference": "cashondelivery ",
                            "PaymentNotes": null,
                            "PaymentCCDetails": null,
                            "PaymentGateway": null,
                            "PayPalEmail": null,
                            "PayPalTransactionID": null,
                            "PayPalProtectionEligibility": false,
                            "Amount": 105,
                            "PaymentDate": "2016-12-16T00:00:00+0000"
                        }
                    ]
                },
                "CurrencyCode": "GBP",
                "SellerUsername": "Magento Test Site",
                "CourierProfileName": null,
                "OrderItems": {
                    "Item": [
                        {
                            "WebProductID": "22",
                            "StockNumber": "AZ11",
                            "ItemNumber": "176",
                            "ProductTitle": "Kawasaki H2R 800cc",
                            "Quantity": 1,
                            "UnitCost": 100,
                            "TaxRate": 40,
                            "TaxCode": null,
                            "UnitCostIncludesTax": "Y",
                            "Weight": 0,
                            "ProductFolderName": null,
                            "CreditReason": null,
                            "CustomMessage1": null,
                            "CustomMessage2": null,
                            "CustomMessage3": null,
                            "LocationId": 4
                        }
                    ]
                },
                "BuyerId": "",
                "StoreId": null,
                "ShipToStore": null,
                "OrderCredits": null,
                "OrderStatus": "Delivered",
                "Flag1": null,
                "Flag2": null,
                "CourierName": null,
                "CourierService": null,
                "CourierServiceCode": null,
                "FulfilmentType": "MERCHANT"
            },
            {
                "OrderType": "Order",
                "OrderSource": "Manual",
                "ESPOrderNo": 1002,
                "InvoiceNumber": "41221",
                "ExternalReference": "",
                "Date": "2016-12-16T13:41:22+0000",
                "CustomerCompany": "",
                "CustomerName": "example",
                "CustomerAddress1": "example",
                "CustomerAddress2": "example",
                "CustomerAddress3": null,
                "CustomerCity": "example",
                "CustomerCounty": "example",
                "CustomerPostcode": "BS11 1NS",
                "CustomerCountry": "UK",
                "CustomerEmail": "example@example.com",
                "CustomerTelephone": "",
                "CustomerFax": null,
                "CustomerReference": null,
                "CustomerNotes": null,
                "DeliveryCompany": "",
                "DeliveryName": "example",
                "DeliveryAddress1": "example",
                "DeliveryAddress2": "example",
                "DeliveryAddress3": null,
                "DeliveryCity": "example",
                "DeliveryCounty": "example",
                "DeliveryPostcode": "BS11 1NS",
                "DeliveryCountry": "UK",
                "DeliveryTelephone": "",
                "ShippingMethod": null,
                "ShippingCost": 0,
                "Insurance": 0,
                "Discount": 0,
                "VoucherCode": null,
                "OrderTotal": 0,
                "PaymentComplete": true,
                "Payments": {
                    "Payment": [
                        {
                            "PaymentMethod": "Cash",
                            "PaymentReference": "1002",
                            "PaymentNotes": null,
                            "PaymentCCDetails": null,
                            "PaymentGateway": null,
                            "PayPalEmail": null,
                            "PayPalTransactionID": null,
                            "PayPalProtectionEligibility": false,
                            "Amount": 10,
                            "PaymentDate": "2016-12-16T00:00:00+0000"
                        },
                        {
                            "PaymentMethod": "Cash",
                            "PaymentReference": "1002 Refund",
                            "PaymentNotes": null,
                            "PaymentCCDetails": null,
                            "PaymentGateway": null,
                            "PayPalEmail": null,
                            "PayPalTransactionID": null,
                            "PayPalProtectionEligibility": false,
                            "Amount": -10,
                            "PaymentDate": "2016-12-16T00:00:00+0000"
                        }
                    ]
                },
                "CurrencyCode": "GBP",
                "SellerUsername": "testuser_esptestus1",
                "CourierProfileName": null,
                "OrderItems": {
                    "Item": [
                        {
                            "WebProductID": "12",
                            "StockNumber": "AZ04",
                            "ItemNumber": "0",
                            "ProductTitle": "Husqvarna Nuda 900rr - Test",
                            "Quantity": 1,
                            "UnitCost": 10,
                            "TaxRate": 20,
                            "TaxCode": null,
                            "UnitCostIncludesTax": "Y",
                            "Weight": 0,
                            "ProductFolderName": null,
                            "CreditReason": null,
                            "CustomMessage1": null,
                            "CustomMessage2": null,
                            "CustomMessage3": null,
                            "LocationId": 4
                        }
                    ]
                },
                "BuyerId": "",
                "StoreId": null,
                "ShipToStore": null,
                "OrderCredits": null,
                "OrderStatus": "Cancelled",
                "Flag1": null,
                "Flag2": null,
                "CourierName": null,
                "CourierService": null,
                "CourierServiceCode": null,
                "FulfilmentType": "MERCHANT"
            },
            {
                "OrderType": "Order",
                "OrderSource": "WWW",
                "ESPOrderNo": 1003,
                "InvoiceNumber": "41222",
                "ExternalReference": "100000137",
                "Date": "2016-12-19T13:29:18+0000",
                "CustomerCompany": "",
                "CustomerName": "Simeone Zaza",
                "CustomerAddress1": "53343 Turin Road",
                "CustomerAddress2": "",
                "CustomerAddress3": null,
                "CustomerCity": "Atlanta",
                "CustomerCounty": "",
                "CustomerPostcode": "32423",
                "CustomerCountry": "GB",
                "CustomerEmail": "1481275517@example.com",
                "CustomerTelephone": "32342432",
                "CustomerFax": null,
                "CustomerReference": null,
                "CustomerNotes": "0",
                "DeliveryCompany": "",
                "DeliveryName": "Simeone Zaza",
                "DeliveryAddress1": "53343 Turin Road",
                "DeliveryAddress2": "",
                "DeliveryAddress3": null,
                "DeliveryCity": "Atlanta",
                "DeliveryCounty": "",
                "DeliveryPostcode": "32423",
                "DeliveryCountry": "GB",
                "DeliveryTelephone": "32342432",
                "ShippingMethod": "flatrate_flatrate",
                "ShippingCost": 5,
                "Insurance": 0,
                "Discount": 0,
                "VoucherCode": null,
                "OrderTotal": 0,
                "PaymentComplete": false,
                "Payments": {
                    "Payment": [
                        {
                            "PaymentMethod": "Credit Card",
                            "PaymentReference": "cashondelivery ",
                            "PaymentNotes": null,
                            "PaymentCCDetails": null,
                            "PaymentGateway": null,
                            "PayPalEmail": null,
                            "PayPalTransactionID": null,
                            "PayPalProtectionEligibility": false,
                            "Amount": 40,
                            "PaymentDate": "2016-12-19T00:00:00+0000"
                        },
                        {
                            "PaymentMethod": "Credit Card",
                            "PaymentReference": null,
                            "PaymentNotes": null,
                            "PaymentCCDetails": null,
                            "PaymentGateway": null,
                            "PayPalEmail": null,
                            "PayPalTransactionID": null,
                            "PayPalProtectionEligibility": false,
                            "Amount": -40,
                            "PaymentDate": "2016-12-19T00:00:00+0000"
                        }
                    ]
                },
                "CurrencyCode": "GBP",
                "SellerUsername": "Magento Test Site",
                "CourierProfileName": null,
                "OrderItems": {
                    "Item": [
                        {
                            "WebProductID": "19",
                            "StockNumber": "AZ08",
                            "ItemNumber": "177",
                            "ProductTitle": "Honda MSX 125",
                            "Quantity": 1,
                            "UnitCost": 35,
                            "TaxRate": 20,
                            "TaxCode": null,
                            "UnitCostIncludesTax": "Y",
                            "Weight": 0,
                            "ProductFolderName": null,
                            "CreditReason": null,
                            "CustomMessage1": null,
                            "CustomMessage2": null,
                            "CustomMessage3": null,
                            "LocationId": 3
                        }
                    ]
                },
                "BuyerId": "",
                "StoreId": null,
                "ShipToStore": null,
                "OrderCredits": null,
                "OrderStatus": "Cancelled",
                "Flag1": null,
                "Flag2": null,
                "CourierName": null,
                "CourierService": null,
                "CourierServiceCode": null,
                "FulfilmentType": "MERCHANT"
            },
            {
                "OrderType": "Order",
                "OrderSource": "WWW",
                "ESPOrderNo": 1004,
                "InvoiceNumber": "41223",
                "ExternalReference": "100000138",
                "Date": "2016-12-19T14:28:33+0000",
                "CustomerCompany": "",
                "CustomerName": "Simeone Zaza",
                "CustomerAddress1": "53343 Turin Road",
                "CustomerAddress2": "",
                "CustomerAddress3": null,
                "CustomerCity": "Atlanta",
                "CustomerCounty": "Georgia",
                "CustomerPostcode": "32423",
                "CustomerCountry": "US",
                "CustomerEmail": "1481275517@example.com",
                "CustomerTelephone": "32342432",
                "CustomerFax": null,
                "CustomerReference": null,
                "CustomerNotes": "23-Apr-2018 12:14:57: aasa\n23-Apr-2018 12:14:24: asaaaa\n23-Apr-2018 12:06:58: aac\n23-Apr-2018 12:05:58: asaaaa\n23-Apr-2018 11:57:36: sddsd\n0",
                "DeliveryCompany": "",
                "DeliveryName": "Simeone Zaza",
                "DeliveryAddress1": "53343 Turin Road",
                "DeliveryAddress2": "",
                "DeliveryAddress3": null,
                "DeliveryCity": "Atlanta",
                "DeliveryCounty": "Georgia",
                "DeliveryPostcode": "32423",
                "DeliveryCountry": "US",
                "DeliveryTelephone": "32342432",
                "ShippingMethod": "flatrate_flatrate",
                "ShippingCost": 5,
                "Insurance": 0,
                "Discount": 0,
                "VoucherCode": null,
                "OrderTotal": 40,
                "PaymentComplete": true,
                "Payments": {
                    "Payment": [
                        {
                            "PaymentMethod": "Credit Card",
                            "PaymentReference": "cashondelivery ",
                            "PaymentNotes": null,
                            "PaymentCCDetails": null,
                            "PaymentGateway": null,
                            "PayPalEmail": null,
                            "PayPalTransactionID": null,
                            "PayPalProtectionEligibility": false,
                            "Amount": 40,
                            "PaymentDate": "2016-12-19T00:00:00+0000"
                        }
                    ]
                },
                "CurrencyCode": "GBP",
                "SellerUsername": "Magento Test Site",
                "CourierProfileName": null,
                "OrderItems": {
                    "Item": [
                        {
                            "WebProductID": "19",
                            "StockNumber": "AZ08",
                            "ItemNumber": "178",
                            "ProductTitle": "Honda MSX 125",
                            "Quantity": 1,
                            "UnitCost": 35,
                            "TaxRate": 40,
                            "TaxCode": null,
                            "UnitCostIncludesTax": "Y",
                            "Weight": 0,
                            "ProductFolderName": null,
                            "CreditReason": null,
                            "CustomMessage1": null,
                            "CustomMessage2": null,
                            "CustomMessage3": null,
                            "LocationId": 4
                        }
                    ]
                },
                "BuyerId": "",
                "StoreId": null,
                "ShipToStore": null,
                "OrderCredits": null,
                "OrderStatus": "On Hold",
                "Flag1": null,
                "Flag2": null,
                "CourierName": null,
                "CourierService": null,
                "CourierServiceCode": null,
                "FulfilmentType": "MERCHANT"
            },
            {
                "OrderType": "Order",
                "OrderSource": "WWW",
                "ESPOrderNo": 1005,
                "InvoiceNumber": "41224",
                "ExternalReference": "100000139",
                "Date": "2016-12-19T14:32:31+0000",
                "CustomerCompany": "",
                "CustomerName": "Simeone Zaza",
                "CustomerAddress1": "53343 Turin Road",
                "CustomerAddress2": "",
                "CustomerAddress3": null,
                "CustomerCity": "Atlanta",
                "CustomerCounty": "Baden-Württemberg",
                "CustomerPostcode": "32423",
                "CustomerCountry": "DE",
                "CustomerEmail": "1481275517@example.com",
                "CustomerTelephone": "32342432",
                "CustomerFax": null,
                "CustomerReference": null,
                "CustomerNotes": "23-Apr-2018 13:55:02: asd\n0",
                "DeliveryCompany": "",
                "DeliveryName": "Simeone Zaza",
                "DeliveryAddress1": "53343 Turin Road",
                "DeliveryAddress2": "",
                "DeliveryAddress3": null,
                "DeliveryCity": "Atlanta",
                "DeliveryCounty": "Baden-Württemberg",
                "DeliveryPostcode": "32423",
                "DeliveryCountry": "DE",
                "DeliveryTelephone": "32342432",
                "ShippingMethod": "flatrate_flatrate",
                "ShippingCost": 5,
                "Insurance": 0,
                "Discount": 0,
                "VoucherCode": null,
                "OrderTotal": 40,
                "PaymentComplete": true,
                "Payments": {
                    "Payment": [
                        {
                            "PaymentMethod": "Credit Card",
                            "PaymentReference": "cashondelivery ",
                            "PaymentNotes": null,
                            "PaymentCCDetails": null,
                            "PaymentGateway": null,
                            "PayPalEmail": null,
                            "PayPalTransactionID": null,
                            "PayPalProtectionEligibility": false,
                            "Amount": 40,
                            "PaymentDate": "2016-12-19T00:00:00+0000"
                        }
                    ]
                },
                "CurrencyCode": "GBP",
                "SellerUsername": "Magento Test Site",
                "CourierProfileName": null,
                "OrderItems": {
                    "Item": [
                        {
                            "WebProductID": "19",
                            "StockNumber": "AZ08",
                            "ItemNumber": "179",
                            "ProductTitle": "Honda MSX 125",
                            "Quantity": 1,
                            "UnitCost": 35,
                            "TaxRate": 50,
                            "TaxCode": null,
                            "UnitCostIncludesTax": "Y",
                            "Weight": 0,
                            "ProductFolderName": null,
                            "CreditReason": null,
                            "CustomMessage1": null,
                            "CustomMessage2": null,
                            "CustomMessage3": null,
                            "LocationId": 3
                        }
                    ]
                },
                "BuyerId": "",
                "StoreId": null,
                "ShipToStore": null,
                "OrderCredits": null,
                "OrderStatus": "On Hold",
                "Flag1": null,
                "Flag2": null,
                "CourierName": null,
                "CourierService": null,
                "CourierServiceCode": null,
                "FulfilmentType": "MERCHANT"
            },
            {
                "OrderType": "Order",
                "OrderSource": "WWW",
                "ESPOrderNo": 1006,
                "InvoiceNumber": "41225",
                "ExternalReference": "100000140",
                "Date": "2016-12-19T14:35:46+0000",
                "CustomerCompany": "",
                "CustomerName": "Simeone Zaza",
                "CustomerAddress1": "53343 Turin Road",
                "CustomerAddress2": "",
                "CustomerAddress3": null,
                "CustomerCity": "Atlanta",
                "CustomerCounty": "Georgia",
                "CustomerPostcode": "32423",
                "CustomerCountry": "US",
                "CustomerEmail": "1481275517@example.com",
                "CustomerTelephone": "32342432",
                "CustomerFax": null,
                "CustomerReference": null,
                "CustomerNotes": "23-Apr-2018 12:41:04: sds\n23-Apr-2018 12:37:31: asasa\n23-Apr-2018 12:37:21: asasa\n0",
                "DeliveryCompany": "",
                "DeliveryName": "Simeone Zaza",
                "DeliveryAddress1": "53343 Turin Road",
                "DeliveryAddress2": "",
                "DeliveryAddress3": null,
                "DeliveryCity": "Atlanta",
                "DeliveryCounty": "Georgia",
                "DeliveryPostcode": "32423",
                "DeliveryCountry": "US",
                "DeliveryTelephone": "32342432",
                "ShippingMethod": "flatrate_flatrate",
                "ShippingCost": 5,
                "Insurance": 0,
                "Discount": 0,
                "VoucherCode": null,
                "OrderTotal": 40,
                "PaymentComplete": true,
                "Payments": {
                    "Payment": [
                        {
                            "PaymentMethod": "Credit Card",
                            "PaymentReference": "cashondelivery ",
                            "PaymentNotes": null,
                            "PaymentCCDetails": null,
                            "PaymentGateway": null,
                            "PayPalEmail": null,
                            "PayPalTransactionID": null,
                            "PayPalProtectionEligibility": false,
                            "Amount": 40,
                            "PaymentDate": "2016-12-19T00:00:00+0000"
                        }
                    ]
                },
                "CurrencyCode": "GBP",
                "SellerUsername": "Magento Test Site",
                "CourierProfileName": null,
                "OrderItems": {
                    "Item": [
                        {
                            "WebProductID": "19",
                            "StockNumber": "AZ08",
                            "ItemNumber": "180",
                            "ProductTitle": "Honda MSX 125",
                            "Quantity": 1,
                            "UnitCost": 35,
                            "TaxRate": 40,
                            "TaxCode": null,
                            "UnitCostIncludesTax": "Y",
                            "Weight": 0,
                            "ProductFolderName": null,
                            "CreditReason": null,
                            "CustomMessage1": null,
                            "CustomMessage2": null,
                            "CustomMessage3": null,
                            "LocationId": 4
                        }
                    ]
                },
                "BuyerId": "",
                "StoreId": null,
                "ShipToStore": null,
                "OrderCredits": null,
                "OrderStatus": "On Hold",
                "Flag1": null,
                "Flag2": null,
                "CourierName": null,
                "CourierService": null,
                "CourierServiceCode": null,
                "FulfilmentType": "MERCHANT"
            },
            {
                "OrderType": "Order",
                "OrderSource": "WWW",
                "ESPOrderNo": 1007,
                "InvoiceNumber": "41226",
                "ExternalReference": "100000141",
                "Date": "2016-12-19T14:41:45+0000",
                "CustomerCompany": "",
                "CustomerName": "Simeone Zaza",
                "CustomerAddress1": "53343 Turin Road",
                "CustomerAddress2": "",
                "CustomerAddress3": null,
                "CustomerCity": "Atlanta",
                "CustomerCounty": "Georgia",
                "CustomerPostcode": "32423",
                "CustomerCountry": "US",
                "CustomerEmail": "1481275517@example.com",
                "CustomerTelephone": "32342432",
                "CustomerFax": null,
                "CustomerReference": null,
                "CustomerNotes": "0",
                "DeliveryCompany": "",
                "DeliveryName": "Simeone Zaza",
                "DeliveryAddress1": "53343 Turin Road",
                "DeliveryAddress2": "",
                "DeliveryAddress3": null,
                "DeliveryCity": "Atlanta",
                "DeliveryCounty": "Georgia",
                "DeliveryPostcode": "32423",
                "DeliveryCountry": "US",
                "DeliveryTelephone": "32342432",
                "ShippingMethod": "flatrate_flatrate",
                "ShippingCost": 5,
                "Insurance": 0,
                "Discount": 0,
                "VoucherCode": null,
                "OrderTotal": 40,
                "PaymentComplete": true,
                "Payments": {
                    "Payment": [
                        {
                            "PaymentMethod": "Credit Card",
                            "PaymentReference": "cashondelivery ",
                            "PaymentNotes": null,
                            "PaymentCCDetails": null,
                            "PaymentGateway": null,
                            "PayPalEmail": null,
                            "PayPalTransactionID": null,
                            "PayPalProtectionEligibility": false,
                            "Amount": 40,
                            "PaymentDate": "2016-12-19T00:00:00+0000"
                        }
                    ]
                },
                "CurrencyCode": "GBP",
                "SellerUsername": "Magento Test Site",
                "CourierProfileName": null,
                "OrderItems": {
                    "Item": [
                        {
                            "WebProductID": "19",
                            "StockNumber": "AZ08",
                            "ItemNumber": "181",
                            "ProductTitle": "Honda MSX 125",
                            "Quantity": 1,
                            "UnitCost": 35,
                            "TaxRate": 40,
                            "TaxCode": null,
                            "UnitCostIncludesTax": "Y",
                            "Weight": 0,
                            "ProductFolderName": null,
                            "CreditReason": null,
                            "CustomMessage1": null,
                            "CustomMessage2": null,
                            "CustomMessage3": null,
                            "LocationId": 3
                        }
                    ]
                },
                "BuyerId": "",
                "StoreId": null,
                "ShipToStore": null,
                "OrderCredits": null,
                "OrderStatus": "Delivered",
                "Flag1": null,
                "Flag2": null,
                "CourierName": null,
                "CourierService": null,
                "CourierServiceCode": null,
                "FulfilmentType": "MERCHANT"
            },
            {
                "OrderType": "Order",
                "OrderSource": "WWW",
                "ESPOrderNo": 1008,
                "InvoiceNumber": "41227",
                "ExternalReference": "100000142",
                "Date": "2016-12-19T14:50:05+0000",
                "CustomerCompany": "",
                "CustomerName": "Simeone Zaza",
                "CustomerAddress1": "53343 Turin Road",
                "CustomerAddress2": "",
                "CustomerAddress3": null,
                "CustomerCity": "Atlanta",
                "CustomerCounty": "",
                "CustomerPostcode": "32423",
                "CustomerCountry": "GB",
                "CustomerEmail": "1481275517@example.com",
                "CustomerTelephone": "32342432",
                "CustomerFax": null,
                "CustomerReference": null,
                "CustomerNotes": "0",
                "DeliveryCompany": "",
                "DeliveryName": "Simeone Zaza",
                "DeliveryAddress1": "53343 Turin Road",
                "DeliveryAddress2": "",
                "DeliveryAddress3": null,
                "DeliveryCity": "Atlanta",
                "DeliveryCounty": "",
                "DeliveryPostcode": "32423",
                "DeliveryCountry": "GB",
                "DeliveryTelephone": "32342432",
                "ShippingMethod": "flatrate_flatrate",
                "ShippingCost": 60,
                "Insurance": 0,
                "Discount": 0,
                "VoucherCode": null,
                "OrderTotal": 540,
                "PaymentComplete": true,
                "Payments": {
                    "Payment": [
                        {
                            "PaymentMethod": "Cash",
                            "PaymentReference": "",
                            "PaymentNotes": null,
                            "PaymentCCDetails": null,
                            "PaymentGateway": null,
                            "PayPalEmail": null,
                            "PayPalTransactionID": null,
                            "PayPalProtectionEligibility": false,
                            "Amount": 540,
                            "PaymentDate": "2016-12-19T00:00:00+0000"
                        }
                    ]
                },
                "CurrencyCode": "GBP",
                "SellerUsername": "Magento Test Site",
                "CourierProfileName": null,
                "OrderItems": {
                    "Item": [
                        {
                            "WebProductID": "114",
                            "StockNumber": "AZ07#sku",
                            "ItemNumber": "182",
                            "ProductTitle": "Lexmoto ZSXF 125",
                            "Quantity": 12,
                            "UnitCost": 40,
                            "TaxRate": 20,
                            "TaxCode": null,
                            "UnitCostIncludesTax": "Y",
                            "Weight": 0,
                            "ProductFolderName": null,
                            "CreditReason": null,
                            "CustomMessage1": null,
                            "CustomMessage2": null,
                            "CustomMessage3": null,
                            "LocationId": 0
                        }
                    ]
                },
                "BuyerId": "",
                "StoreId": null,
                "ShipToStore": null,
                "OrderCredits": null,
                "OrderStatus": "Delivered",
                "Flag1": null,
                "Flag2": null,
                "CourierName": null,
                "CourierService": null,
                "CourierServiceCode": null,
                "FulfilmentType": "MERCHANT"
            },
            {
                "OrderType": "Order",
                "OrderSource": "WWW",
                "ESPOrderNo": 1009,
                "InvoiceNumber": "41228",
                "ExternalReference": "100000143",
                "Date": "2016-12-19T14:58:30+0000",
                "CustomerCompany": "",
                "CustomerName": "Simeone Zaza",
                "CustomerAddress1": "53343 Turin Road",
                "CustomerAddress2": "",
                "CustomerAddress3": null,
                "CustomerCity": "Atlanta",
                "CustomerCounty": "",
                "CustomerPostcode": "32423",
                "CustomerCountry": "GB",
                "CustomerEmail": "1481275517@example.com",
                "CustomerTelephone": "32342432",
                "CustomerFax": null,
                "CustomerReference": null,
                "CustomerNotes": "0",
                "DeliveryCompany": "",
                "DeliveryName": "Simeone Zaza",
                "DeliveryAddress1": "53343 Turin Road",
                "DeliveryAddress2": "",
                "DeliveryAddress3": null,
                "DeliveryCity": "Atlanta",
                "DeliveryCounty": "",
                "DeliveryPostcode": "32423",
                "DeliveryCountry": "GB",
                "DeliveryTelephone": "32342432",
                "ShippingMethod": "flatrate_flatrate",
                "ShippingCost": 5,
                "Insurance": 0,
                "Discount": 0,
                "VoucherCode": null,
                "OrderTotal": 45,
                "PaymentComplete": true,
                "Payments": {
                    "Payment": [
                        {
                            "PaymentMethod": "Credit Card",
                            "PaymentReference": "cashondelivery ",
                            "PaymentNotes": null,
                            "PaymentCCDetails": null,
                            "PaymentGateway": null,
                            "PayPalEmail": null,
                            "PayPalTransactionID": null,
                            "PayPalProtectionEligibility": false,
                            "Amount": 45,
                            "PaymentDate": "2016-12-19T00:00:00+0000"
                        }
                    ]
                },
                "CurrencyCode": "GBP",
                "SellerUsername": "Magento Test Site",
                "CourierProfileName": null,
                "OrderItems": {
                    "Item": [
                        {
                            "WebProductID": "114",
                            "StockNumber": "AZ07#sku",
                            "ItemNumber": "183",
                            "ProductTitle": "Lexmoto ZSXF 125",
                            "Quantity": 1,
                            "UnitCost": 40,
                            "TaxRate": 20,
                            "TaxCode": null,
                            "UnitCostIncludesTax": "Y",
                            "Weight": 0,
                            "ProductFolderName": null,
                            "CreditReason": null,
                            "CustomMessage1": null,
                            "CustomMessage2": null,
                            "CustomMessage3": null,
                            "LocationId": 3
                        }
                    ]
                },
                "BuyerId": "",
                "StoreId": null,
                "ShipToStore": null,
                "OrderCredits": null,
                "OrderStatus": "Delivered",
                "Flag1": null,
                "Flag2": null,
                "CourierName": null,
                "CourierService": null,
                "CourierServiceCode": null,
                "FulfilmentType": "MERCHANT"
            }
        ]
    },
    "PaginationResult": {
        "TotalNumberOfPages": 339,
        "TotalNumberOfEntries": 3382
    }

}
    return {
        fetch: jest.fn(() => Promise.resolve(order)),
    };
});


describe(
    'Order list tests:', () => {
        it('Renders a component with with a list', () => {

            OrderList.contextTypes = {
                router: PropTypes.object
            };
            const childContextTypes = {
                router: PropTypes.object
            };
            const store = mockStore(orderStore);
            const context = createRouterContext();
            const wrapper = shallow(
                <Provider store={store}>
                    <OrderList store={store}/>
                </Provider>, { context, childContextTypes });
            expect(wrapper).toMatchSnapshot();
        });
        // it('Renders a component with 1 button', () => {
        //     const initialState = {
        //         ordersFilterReducer: {
        //             pageNumber: 1
        //         }
        //     };
        //     const store = mockStore(initialState);
        //     const wrapper = mount(
        //         <Provider store={store}>
        //             <OrderList/>
        //         </Provider>
        //     );
        //     expect(wrapper).toMatchSnapshot();
        // });
    }
);
